version: "3.9"
services:
  api:
    build: .
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://walletapi:p0stgr3s@db:5432/walletapi
  db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_USER: walletapi
    volumes:
      - ./internal/repository/seed.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U walletapi"]
      interval: 3s
      timeout: 5s
      retries: 5
  db_ui:
    image: sosedoff/pgweb:0.13.1
    depends_on: 
      db:
        condition: service_healthy
    ports: 
      - "8081:8081" 
    environment:
      - PGWEB_DATABASE_URL=postgresql://walletapi:p0stgr3s@db:5432/walletapi?sslmode=disable